# Agenda
* Numpy
* Pandas
* Lab


# Introduction


## Download this notebook for our code-along:

From our class GitHub repository "notebooks" directory, download the file "02_numpy_and_pandas.ipynb".  Move this to a convenient place where you are grouping your class related materials.


# Introduction to Numpy ("num-pi")

* Overview
* ndarray
* Indexing and Slicing

More info: [http://wiki.scipy.org/Tentative_NumPy_Tutorial](http://wiki.scipy.org/Tentative_NumPy_Tutorial)


## Numpy Overview

* Why use the Numpy package for Data?
    * It makes our data science life easier!!
        * Numpy brings *decades* of C math into Python!
        * Numpy provides a wrapper for extensive C/C++/Fortran codebases, used for data analysis functionality
        * NDAarray allows easy vectorized math and broadcasting (i.e. functions for vector elements of different shapes)

In [3]:
## from numpy import * #Load all the numpy packages
%matplotlib inline
import numpy as np



### A Note About "import as"

    import * 
This loads all submodules. Note: this is a waste of memory when incorporated into deployed code. 
We'll use it here by example - it's fine to use for learning purposes and legibility.

As we'll see later, the proper convention is to use:

    import numpy as np
    
And then to specifically call needed methods:

![](https://www.evernote.com/shard/s97/sh/7b2e1c08-16c3-4cef-9d9d-b329c3559972/b0e9440ee858b94049b37b0308afd2eb/deep/0/lec_03_numpy_and_pandas_draft.png)

### Creating ndarrays

An array object represents a multidimensional, homogeneous array of fixed-size items. 

In [4]:
# Creating arrays
a = np.zeros((3))
b = np.ones((2,3))
c = np.random.randint(1,10,(2,3,4))
d = np.arange(0,11,1)

What are these functions?

    arange?

In [5]:
# Note the way each array is printed:
print("a: ",a)
print("b: ",b)
print("c: ",c)
print("d: ",d)

('a: ', array([ 0.,  0.,  0.]))
('b: ', array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]]))
('c: ', array([[[6, 3, 5, 1],
        [9, 2, 7, 9],
        [1, 6, 1, 8]],

       [[3, 8, 1, 9],
        [8, 5, 6, 6],
        [5, 8, 1, 4]]]))
('d: ', array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))


In [ ]:
## Arithmetic in arrays is element wise

In [6]:
>>> a = np.array( [20,30,40,50] )
>>> b = np.arange( 4 )
>>> b

array([0, 1, 2, 3])

In [7]:
>>> c = a-b
>>> c

array([20, 29, 38, 47])

In [ ]:
>>> b**2

## Indexing, Slicing and Iterating

In [8]:
# one-dimensional arrays work like lists:
a = np.arange(10)**2

In [9]:
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [10]:
a[2:5]

array([ 4,  9, 16])

In [ ]:
# Multidimensional arrays use tuples with commas for indexing
# with (row,column) conventions beginning, as always in Python, from 0

In [11]:
b = np.random.randint(1,100,(4,4))

In [12]:
b

array([[75, 22, 87, 54],
       [37, 24,  4, 71],
       [49, 34, 46,  7],
       [61, 19, 35,  9]])

In [ ]:
# Guess the output
print(b[2,3])


In [ ]:
# Guess the output
print(b[0,0])


In [ ]:
# Guess the output
b[0:3,1]

In [ ]:
#Guess the output
b[:,1]

In [ ]:
#Guess the output
b[1:3,:]

# Introduction to Pandas

**Pandas, Know it! Love it! We will use it extensively.**

Will allow us to use short lines of code to do important manipulation and viewing of our data
* Object Creation
* Viewing data
* Selection
* Missing data
* Grouping
* Reshaping
* Time series
* Plotting
* i/o
 

_pandas.pydata.org_

## Pandas Overview

_Source: [pandas.pydata.org](http://pandas.pydata.org/pandas-docs/stable/10min.html)_

In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [17]:
dates = pd.date_range('20140101',periods=6)
dates

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06'],
              dtype='datetime64[ns]', freq='D')

In [18]:
df = pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))
z = pd.DataFrame(index = df.index, columns = df.columns)
df.columns

Index([u'A', u'B', u'C', u'D'], dtype='object')

In [19]:
# Index, columns, underlying numpy data
df

A         B         C         D
2014-01-01 -0.300241 -0.163407 -2.347658  0.207318
2014-01-02 -0.432411 -0.830630 -0.428231  1.003104
2014-01-03 -0.128845  1.104819  0.917218  0.676463
2014-01-04 -1.645786 -0.211089 -2.485406 -1.981405
2014-01-05 -0.859640 -1.162219 -0.832233 -1.382583
2014-01-06 -1.356763 -0.466915  0.882194  2.240638

In [20]:
df.T


2014-01-01  2014-01-02  2014-01-03  2014-01-04  2014-01-05  2014-01-06
A   -0.300241   -0.432411   -0.128845   -1.645786   -0.859640   -1.356763
B   -0.163407   -0.830630    1.104819   -0.211089   -1.162219   -0.466915
C   -2.347658   -0.428231    0.917218   -2.485406   -0.832233    0.882194
D    0.207318    1.003104    0.676463   -1.981405   -1.382583    2.240638

In [21]:
df

A         B         C         D
2014-01-01 -0.300241 -0.163407 -2.347658  0.207318
2014-01-02 -0.432411 -0.830630 -0.428231  1.003104
2014-01-03 -0.128845  1.104819  0.917218  0.676463
2014-01-04 -1.645786 -0.211089 -2.485406 -1.981405
2014-01-05 -0.859640 -1.162219 -0.832233 -1.382583
2014-01-06 -1.356763 -0.466915  0.882194  2.240638

In [22]:
temp = df.T
temp

2014-01-01  2014-01-02  2014-01-03  2014-01-04  2014-01-05  2014-01-06
A   -0.300241   -0.432411   -0.128845   -1.645786   -0.859640   -1.356763
B   -0.163407   -0.830630    1.104819   -0.211089   -1.162219   -0.466915
C   -2.347658   -0.428231    0.917218   -2.485406   -0.832233    0.882194
D    0.207318    1.003104    0.676463   -1.981405   -1.382583    2.240638

In [ ]:
df = df.T

In [23]:
df2 = pd.DataFrame({ 'A' : 1.,
                         'B' : pd.Timestamp('20130102'),
                         'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                         'D' : np.array([3] * 4,dtype='int32'),
                         'E' : 'foo' })
    

df2

A          B    C  D    E
0  1.0 2013-01-02  1.0  3  foo
1  1.0 2013-01-02  1.0  3  foo
2  1.0 2013-01-02  1.0  3  foo
3  1.0 2013-01-02  1.0  3  foo

In [24]:
# With specific dtypes
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E            object
dtype: object

#### Viewing Data

In [25]:
df

A         B         C         D
2014-01-01 -0.300241 -0.163407 -2.347658  0.207318
2014-01-02 -0.432411 -0.830630 -0.428231  1.003104
2014-01-03 -0.128845  1.104819  0.917218  0.676463
2014-01-04 -1.645786 -0.211089 -2.485406 -1.981405
2014-01-05 -0.859640 -1.162219 -0.832233 -1.382583
2014-01-06 -1.356763 -0.466915  0.882194  2.240638

In [26]:
df.head()


A         B         C         D
2014-01-01 -0.300241 -0.163407 -2.347658  0.207318
2014-01-02 -0.432411 -0.830630 -0.428231  1.003104
2014-01-03 -0.128845  1.104819  0.917218  0.676463
2014-01-04 -1.645786 -0.211089 -2.485406 -1.981405
2014-01-05 -0.859640 -1.162219 -0.832233 -1.382583

In [28]:
df.tail(3)

A         B         C         D
2014-01-04 -1.645786 -0.211089 -2.485406 -1.981405
2014-01-05 -0.859640 -1.162219 -0.832233 -1.382583
2014-01-06 -1.356763 -0.466915  0.882194  2.240638

In [29]:
df.index

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06'],
              dtype='datetime64[ns]', freq='D')

In [30]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.787281 -0.288240 -0.715686  0.127256
std    0.610451  0.781294  1.490708  1.566371
min   -1.645786 -1.162219 -2.485406 -1.981405
25%   -1.232482 -0.739701 -1.968802 -0.985108
50%   -0.646026 -0.339002 -0.630232  0.441890
75%   -0.333283 -0.175328  0.554588  0.921443
max   -0.128845  1.104819  0.917218  2.240638

In [31]:
df

A         B         C         D
2014-01-01 -0.300241 -0.163407 -2.347658  0.207318
2014-01-02 -0.432411 -0.830630 -0.428231  1.003104
2014-01-03 -0.128845  1.104819  0.917218  0.676463
2014-01-04 -1.645786 -0.211089 -2.485406 -1.981405
2014-01-05 -0.859640 -1.162219 -0.832233 -1.382583
2014-01-06 -1.356763 -0.466915  0.882194  2.240638

In [35]:
z = df.sort_values(by="B")
z


A         B         C         D
2014-01-05 -0.859640 -1.162219 -0.832233 -1.382583
2014-01-02 -0.432411 -0.830630 -0.428231  1.003104
2014-01-06 -1.356763 -0.466915  0.882194  2.240638
2014-01-04 -1.645786 -0.211089 -2.485406 -1.981405
2014-01-01 -0.300241 -0.163407 -2.347658  0.207318
2014-01-03 -0.128845  1.104819  0.917218  0.676463

### Selection

In [36]:
df[['A','B']]

A         B
2014-01-01 -0.300241 -0.163407
2014-01-02 -0.432411 -0.830630
2014-01-03 -0.128845  1.104819
2014-01-04 -1.645786 -0.211089
2014-01-05 -0.859640 -1.162219
2014-01-06 -1.356763 -0.466915

In [40]:
df[0:3]

A         B         C         D
2014-01-01 -0.300241 -0.163407 -2.347658  0.207318
2014-01-02 -0.432411 -0.830630 -0.428231  1.003104
2014-01-03 -0.128845  1.104819  0.917218  0.676463

In [41]:
# By label
df.loc[dates[0]]

A   -0.300241
B   -0.163407
C   -2.347658
D    0.207318
Name: 2014-01-01 00:00:00, dtype: float64

In [44]:
# multi-axis by label
df.loc[:,['A','B']]

A         B
2014-01-01 -0.300241 -0.163407
2014-01-02 -0.432411 -0.830630
2014-01-03 -0.128845  1.104819
2014-01-04 -1.645786 -0.211089
2014-01-05 -0.859640 -1.162219
2014-01-06 -1.356763 -0.466915

In [ ]:
# Date Range
df.loc['20140102':'20140104',['B']]

In [ ]:
# Fast access to scalar
df.at[dates[1],'B']

### Operations

In [ ]:
df.describe()

In [ ]:
df.mean(),df.mean(1) # Operation on two different axes
# there are pandas' methods for min, max etc. as well

### Boolean Indexing

In [ ]:
df

In [ ]:
df[df.A < 0] # Basically a 'where' operation

In [ ]:
df.A < 0

In [ ]:
# Two conditions added together
df[(df.A < 0) & (df.B > .5) ]

In [ ]:
# Two conditions ORed together
df[(df.A < -1) | (df.D > 0)]

### Merge

In [ ]:
np.random.randn(10,4)

In [ ]:
##Concatenating pandas objects together
# create a dataframe to use as an example
df2 = pd.DataFrame(np.random.randn(10,4))
df2

In [ ]:
# Break it into pieces
pieces = [df2[:3], df2[3:7],df2[7:]]
pieces

In [ ]:
pd.concat(pieces)

In [ ]:
# Also can "Join" and "Append"

### Setting

In [ ]:
df_posA = df.copy() # Without "copy" it would act on the dataset

df_posA[df_posA.A < 0] = -1*df_posA

In [ ]:
df_posA

In [ ]:
#Setting new column aligns data by index
s1 = pd.Series([1,2,3,4,5,6],index=pd.date_range('20140102',periods=6))

In [ ]:
s1

In [ ]:
df['F'] = s1

In [ ]:
df

### Missing Data

In [ ]:
# Add a column with missing data
df1 = df.reindex(index=dates[0:4],columns=list(df.columns) + ['E'])

In [ ]:
df1.loc[dates[0]:dates[1],'E'] = 1

In [ ]:
df1

In [ ]:
# find where values are null
pd.isnull(df1)

### Applying functions

In [ ]:
df

In [ ]:
df.apply(np.cumsum)

In [ ]:
df.apply(lambda x: x.max() - x.min())

In [ ]:
# Built in string methods
s = pd.Series(['A', 'B', 'C', 'Aaba', 'Baca', np.nan, 'CABA', 'dog', 'cat'])
s.str.lower()

### Grouping


In [ ]:
df3 = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar',
                       'foo', 'bar', 'foo', 'foo'],
                       'B' : ['one', 'one', 'two', 'three',
                             'two', 'two', 'one', 'three'],
                       'C' : np.random.randn(8),
                       'D' : np.random.randn(8)})

In [ ]:
df3

In [ ]:
df3.groupby(['A','B']).sum()

### Reshaping

In [ ]:
# You can also stack or unstack levels

In [ ]:
a = df3.groupby(['A','B']).sum()

In [ ]:
# Pivot Tables
# pd.pivot_table(df3,values=['C','D'],rows=['A'],cols=['B'])

### Time Series


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# 100 Seconds starting on January 1st
rng = pd.date_range('1/1/2014', periods=100, freq='S')

In [ ]:
# Give each second a random value
ts = pd.Series(np.random.randint(0, 500, len(rng)), index=rng)

In [ ]:
ts

In [ ]:
# Built in resampling
ts.resample('1Min',how='mean') # Resample secondly to 1Minutely

In [ ]:
# Many additional time series features
# ts. #use tab

### Plotting


In [ ]:
ts.plot()

In [ ]:
def randwalk(startdate,points):
    ts = pd.Series(np.random.randn(points), index=pd.date_range(startdate, periods=points))
    ts=ts.cumsum()
    ts.plot()
    return(ts)

In [ ]:
# Using pandas to make a simple random walker by repeatedly running:
a=randwalk('1/1/2012',1000)

In [ ]:
# Pandas plot function will print with labels as default

In [ ]:
df = pd.DataFrame(np.random.randn(100, 4), index=ts.index,columns=['A', 'B', 'C', 'D'])
df = df.cumsum()
plt.figure();df.plot();plt.legend(loc='best') #

### I/O
I/O is straightforward with, for example, pd.read_csv or df.to_csv

# Next Steps

**Recommended Resources**

Name | Description
--- | ---
[Official Pandas Tutorials](http://pandas.pydata.org/pandas-docs/stable/tutorials.html) | Wes & Company's selection of tutorials and lectures
[Julia Evans Pandas Cookbook](https://github.com/jvns/pandas-cookbook) | Great resource with examples from weather, bikes and 311 calls
[Learn Pandas Tutorials](https://bitbucket.org/hrojas/learn-pandas) | A great series of Pandas tutorials from Dave Rojas
[Research Computing Python Data PYNBs](https://github.com/ResearchComputing/Meetup-Fall-2013/tree/master/python) | A super awesome set of python notebooks from a meetup-based course exclusively devoted to pandas